name: openscribe
description: A better editor.

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.6
  flutter_acrylic: ^1.1.3
  flutter_svg: ^2.0.7
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  file_picker: ^5.5.0
  uuid: ^4.1.0
  adaptive_theme: ^3.4.0
  flutter_hsvcolor_picker: ^1.5.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  printing: ^5.11.0
  syncfusion_flutter_pdfviewer: ^23.1.40
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/langs/
